name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Node install
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Yarn install
      run: yarn install

    - name: Build
      run: yarn run build

    # TODO: remove comment after fixing tests
    # - name: Run tests
    #   run: npm run test

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: build-files
        path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:

    - name: Download
      uses: actions/download-artifact@v2
      with:
        name: build-files
        path: ./build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: pages
        publish_dir: ./build
